version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: labverse_postgres
    restart: always
    environment:
      POSTGRES_DB: admin_panel
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5433:5432"